// Serializes content/data.json into content-data.js — the plain <script>
// file every public HTML page loads before data.js. Regenerated on every
// admin save so the static site never has to fetch JSON at runtime.

function generate(data) {
  const out = [
    '// AUTO-GENERATED by the zjCanvas admin (/admin) — do not edit by hand.',
    '// Source of truth is content/data.json. Any manual edit here will be',
    '// overwritten the next time something is saved in the admin panel.',
    '',
    `const SITE_SETTINGS = ${JSON.stringify(data.settings, null, 2)};`,
    '',
    `const LOGO_ITEMS = ${JSON.stringify(data.logos, null, 2)};`,
    '',
    `const POSTER_ITEMS = ${JSON.stringify(data.posters, null, 2)};`,
    '',
    `const REEL_ITEMS = ${JSON.stringify(data.reels, null, 2)};`,
    '',
    `const CAROUSEL_ITEMS = ${JSON.stringify(data.carousels, null, 2)};`,
    '',
    `const BROCHURE_ITEMS = ${JSON.stringify(data.brochures, null, 2)};`,
    '',
    `const TESTIMONIALS = ${JSON.stringify(data.testimonials, null, 2)};`,
    '',
    `const TOOLS = ${JSON.stringify(data.tools, null, 2)};`,
    '',
  ];
  return out.join('\n');
}

module.exports = { generate };
